-- MySQL Script generated by MySQL Workbench
-- Sat Nov 15 09:43:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema metahogar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema metahogar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metahogar` DEFAULT CHARACTER SET utf8mb4 ;
USE `metahogar` ;

-- -----------------------------------------------------
-- Table `metahogar`.`agencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`agencia` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`agencia` (
  `idAgencia` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(120) NOT NULL,
  `Contacto` VARCHAR(120) NOT NULL,
  `Telefono` VARCHAR(25) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(255) NOT NULL,
  `EstadoValidacion` ENUM('PENDIENTE', 'APROBADA', 'RECHAZADA') NOT NULL DEFAULT 'PENDIENTE',
  PRIMARY KEY (`idAgencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`servicio` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`servicio` (
  `idServicio` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(120) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Costo` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `Agencia_idAgencia` INT(11) NOT NULL,
  `Activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idServicio`),
  INDEX `idx_servicio_agencia` (`Agencia_idAgencia` ASC) VISIBLE,
  CONSTRAINT `fk_Servicio_Agencia`
    FOREIGN KEY (`Agencia_idAgencia`)
    REFERENCES `metahogar`.`agencia` (`idAgencia`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`usuario` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NOT NULL,
  `ApellidoP` VARCHAR(60) NOT NULL,
  `ApellidoM` VARCHAR(60) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `Telefono` VARCHAR(25) NOT NULL,
  `FechaRegistro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `Activo` TINYINT(1) NOT NULL DEFAULT 1,
  `Tipo` VARCHAR(45) NOT NULL,
  `FechaActualizacion` DATETIME NOT NULL,
  `IntentosFallidos` INT(11) NOT NULL DEFAULT 0,
  `BloqueadoHasta` DATETIME NOT NULL,
  `PasswordResetToken` VARCHAR(64) NOT NULL,
  `PasswordResetExpires` DATETIME NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `PasswordResetToken` (`PasswordResetToken` ASC) VISIBLE,
  INDEX `idx_usuario_email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`cita` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`cita` (
  `idCita` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT(11) NOT NULL,
  `Servicio_idServicio` INT(11) NOT NULL,
  `FechaHora` DATETIME NOT NULL,
  `Estado` ENUM('AGENDADA', 'CONFIRMADA', 'CANCELADA', 'REALIZADA') NOT NULL DEFAULT 'AGENDADA',
  `Notas` TEXT NOT NULL,
  `FechaRegistro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idCita`),
  INDEX `fk_Cita_Servicio` (`Servicio_idServicio` ASC) VISIBLE,
  INDEX `idx_cita_estado` (`Estado` ASC) VISIBLE,
  INDEX `idx_cita_usuario_fecha` (`Usuario_idUsuario` ASC, `FechaHora` ASC) VISIBLE,
  CONSTRAINT `fk_Cita_Servicio`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `metahogar`.`servicio` (`idServicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cita_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `metahogar`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`contenido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`contenido` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`contenido` (
  `idContenido` INT(11) NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('NOTICIA', 'ARTICULO', 'BLOG', 'SITIO_INTERES') NOT NULL,
  `Titulo` VARCHAR(200) NOT NULL,
  `Cuerpo` TEXT NOT NULL,
  `AutorUsuario_id` INT(11) NOT NULL,
  `FechaPublicacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `Activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idContenido`),
  INDEX `fk_Contenido_Autor` (`AutorUsuario_id` ASC) VISIBLE,
  INDEX `idx_contenido_tipo_fecha` (`Tipo` ASC, `FechaPublicacion` ASC) VISIBLE,
  CONSTRAINT `fk_Contenido_Autor`
    FOREIGN KEY (`AutorUsuario_id`)
    REFERENCES `metahogar`.`usuario` (`idUsuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`incidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`incidencia` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`incidencia` (
  `idIncidencia` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT(11) NOT NULL,
  `Titulo` VARCHAR(150) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Estado` ENUM('ABIERTA', 'EN_PROGRESO', 'RESUELTA', 'CERRADA') NOT NULL DEFAULT 'ABIERTA',
  `FechaRegistro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idIncidencia`),
  INDEX `fk_Incidencia_Usuario` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Incidencia_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `metahogar`.`usuario` (`idUsuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`multimedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`multimedia` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`multimedia` (
  `idMedia` INT(11) NOT NULL AUTO_INCREMENT,
  `Contenido_idContenido` INT(11) NOT NULL,
  `Tipo` ENUM('IMAGEN', 'VIDEO', 'DOCUMENTO') NOT NULL DEFAULT 'IMAGEN',
  `Ruta` VARCHAR(255) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMedia`),
  INDEX `fk_Multimedia_Contenido` (`Contenido_idContenido` ASC) VISIBLE,
  CONSTRAINT `fk_Multimedia_Contenido`
    FOREIGN KEY (`Contenido_idContenido`)
    REFERENCES `metahogar`.`contenido` (`idContenido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`notificacion` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`notificacion` (
  `idNotificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT(11) NOT NULL,
  `Titulo` VARCHAR(150) NOT NULL,
  `Mensaje` TEXT NOT NULL,
  `Leida` TINYINT(1) NOT NULL DEFAULT 0,
  `FechaEnvio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idNotificacion`),
  INDEX `fk_Notificacion_Usuario` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `metahogar`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`producto` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`producto` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `Existencia` INT(11) NOT NULL DEFAULT 0,
  `Activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`rol` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`rol` (
  `idRol` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`sugerencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`sugerencia` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`sugerencia` (
  `idSugerencia` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT(11) NOT NULL,
  `Titulo` VARCHAR(150) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Estado` ENUM('PENDIENTE', 'EN_PROCESO', 'ATENDIDA', 'CERRADA') NOT NULL DEFAULT 'PENDIENTE',
  `FechaRegistro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idSugerencia`),
  INDEX `fk_Sugerencia_Usuario` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Sugerencia_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `metahogar`.`usuario` (`idUsuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metahogar`.`usuariorol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metahogar`.`usuariorol` ;

CREATE TABLE IF NOT EXISTS `metahogar`.`usuariorol` (
  `idUsuarioRol` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT(11) NOT NULL,
  `Rol_idRol` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuarioRol`),
  INDEX `fk_UsuarioRol_Usuario` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_UsuarioRol_Rol` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_UsuarioRol_Rol`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `metahogar`.`rol` (`idRol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UsuarioRol_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `metahogar`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;

USE `metahogar` ;

-- -----------------------------------------------------
-- procedure sp_reporteCitasPorUsuario
-- -----------------------------------------------------

USE `metahogar`;
DROP procedure IF EXISTS `metahogar`.`sp_reporteCitasPorUsuario`;

DELIMITER $$
USE `metahogar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_reporteCitasPorUsuario`(IN `pUsuario` INT)
BEGIN
    SELECT c.idCita, s.Nombre AS Servicio, c.FechaHora, c.Estado
    FROM Cita c
    INNER JOIN Servicio s ON c.Servicio_idServicio = s.idServicio
    WHERE c.Usuario_idUsuario = pUsuario
    ORDER BY c.FechaHora DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_reporteIncidenciasAbiertas
-- -----------------------------------------------------

USE `metahogar`;
DROP procedure IF EXISTS `metahogar`.`sp_reporteIncidenciasAbiertas`;

DELIMITER $$
USE `metahogar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_reporteIncidenciasAbiertas`()
BEGIN
    SELECT i.idIncidencia, i.Titulo, i.Descripcion, i.FechaRegistro, u.Nombre
    FROM Incidencia i
    LEFT JOIN Usuario u ON i.Usuario_idUsuario = u.idUsuario
    WHERE i.Estado = 'ABIERTA'
    ORDER BY i.FechaRegistro ASC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_reporteNotificacionesPendientes
-- -----------------------------------------------------

USE `metahogar`;
DROP procedure IF EXISTS `metahogar`.`sp_reporteNotificacionesPendientes`;

DELIMITER $$
USE `metahogar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_reporteNotificacionesPendientes`(IN `pUsuario` INT)
BEGIN
    SELECT idNotificacion, Titulo, Mensaje, FechaEnvio
    FROM Notificacion
    WHERE Usuario_idUsuario = pUsuario AND Leida = 0
    ORDER BY FechaEnvio DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_reporteSugerenciasPorEstado
-- -----------------------------------------------------

USE `metahogar`;
DROP procedure IF EXISTS `metahogar`.`sp_reporteSugerenciasPorEstado`;

DELIMITER $$
USE `metahogar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_reporteSugerenciasPorEstado`(IN `pEstado` VARCHAR(20))
BEGIN
    SELECT s.idSugerencia, s.Titulo, s.Estado, s.FechaRegistro, u.Nombre AS Usuario
    FROM Sugerencia s
    LEFT JOIN Usuario u ON s.Usuario_idUsuario = u.idUsuario
    WHERE s.Estado = pEstado
    ORDER BY s.FechaRegistro DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_reporteVentasPorProducto
-- -----------------------------------------------------

USE `metahogar`;
DROP procedure IF EXISTS `metahogar`.`sp_reporteVentasPorProducto`;

DELIMITER $$
USE `metahogar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_reporteVentasPorProducto`()
BEGIN
    SELECT p.Nombre AS Producto, SUM(d.Cantidad) AS TotalVendido, SUM(d.Cantidad * d.PrecioUnitario) AS Ingresos
    FROM DetallePedido d
    INNER JOIN Producto p ON d.Producto_idProducto = p.idProducto
    INNER JOIN Pedido pe ON d.Pedido_idPedido = pe.idPedido
    WHERE pe.Estado IN ('PAGADO','ENVIADO','ENTREGADO')
    GROUP BY p.idProducto
    ORDER BY Ingresos DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_validarAgencia
-- -----------------------------------------------------

USE `metahogar`;
DROP procedure IF EXISTS `metahogar`.`sp_validarAgencia`;

DELIMITER $$
USE `metahogar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_validarAgencia`(IN `pAgencia` INT, IN `pEstado` VARCHAR(20))
BEGIN
    UPDATE Agencia SET EstadoValidacion = pEstado WHERE idAgencia = pAgencia;
    SELECT CONCAT('Agencia ', pAgencia, ' actualizada a estado: ', pEstado) AS Mensaje;
END$$

DELIMITER ;
USE `metahogar`;

DELIMITER $$

USE `metahogar`$$
DROP TRIGGER IF EXISTS `metahogar`.`trg_usuario_update` $$
USE `metahogar`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `metahogar`.`trg_usuario_update`
BEFORE UPDATE ON `metahogar`.`usuario`
FOR EACH ROW
BEGIN
    SET NEW.FechaActualizacion = NOW();
END$$


USE `metahogar`$$
DROP TRIGGER IF EXISTS `metahogar`.`trg_producto_update` $$
USE `metahogar`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `metahogar`.`trg_producto_update`
AFTER UPDATE ON `metahogar`.`producto`
FOR EACH ROW
BEGIN
    DECLARE vUsuario VARCHAR(100);
    SELECT USER() INTO vUsuario;
    IF (NEW.Existencia <> OLD.Existencia) THEN
        INSERT INTO AuditoriaProducto(idProducto, Cambio, Usuario)
        VALUES(NEW.idProducto, NEW.Existencia - OLD.Existencia, vUsuario);
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
